server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: book
          uri: lb://book
          predicates:
            - Path=/books/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/users/**
        - id: borrowing
          uri: lb://borrowing
          predicates:
            - Path=/borrowings/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: api-gateway:${server.port}
